version: '3'
services:
  oracle-partitions:
    image: gvenzl/oracle-xe:21
    container_name: oracle-partitions
    environment:
      - ORACLE_PASSWORD=PASSPASS
    volumes:
      - ./csv:/tmp/csv
      - ./scripts:/tmp/scripts
      - ./data:/opt/oracle/oradata
    ports: 
      - "1521:1521"